[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[[redirects]]
  from = "/article/:slug"
  to = "/article/detail.html"
  status = 200

[[redirects]]
  from = "/article"
  to = "/article/index.html"
  status = 200

[[redirects]]
  from = "/article/"
  to = "/article/index.html"
  status = 200
